service: benharloewebsite

provider:
  name: aws
  runtime: nodejs4.3
  environment:
    SLS_STAGE: ${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "sns:Publish"
      Resource:
        - "arn:aws:sns:us-east-1:531830737663:professionalWebsite"

functions:
  main:
    handler: contact/index.handler
    events:
      - http:
          path: /
          method: post
          cors: true